#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 SS-Rule-Snippet：https://github.com/Hackl0us/SS-Rule-Snippet/blob/master/LAZY_RULES/clash.yaml
## 或者官方Github文档 https://github.com/Dreamacro/clash/blob/master/README.md
#---------------------------------------------------#

port: 1080
socks-port: 1081
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

Proxy:
  - name: "v2ray-proxy"
    type: vmess
    server: v2ray.server.com
    port: 10086
    uuid: 60ca58e9-003e-4c01-98de-c2223ae49153
    alterId: 64
    cipher: auto

Proxy Group:

Rule:
- DOMAIN-SUFFIX,google.com,DIRECT
- DOMAIN-KEYWORD,google,DIRECT
- DOMAIN,google.com,DIRECT
- DOMAIN-SUFFIX,ad.com,REJECT
- GEOIP,CN,DIRECT
- MATCH,DIRECT
